---
title: "git_00"
author: "Brianna Olvera"
date: "09/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.

Commit at each point as required by the assignment! Finally you can drag/drop the files into Canvas or you will push this repository to you github account, you can send me the URL.

<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

How doth the little crocodile  
Improve his shining tail,  
And pour the waters of the Nile  
On every golden scale!  
How cheerfully he seems to grin  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!"  "

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

When I see birches bend to left and right    
Across the lines of straighter darker trees,  
I like to think some boy's been swinging them.  
But swinging doesn't bend them down to stay  
As ice-storms do. Often you must have seen them  
Loaded with ice a sunny winter morning  
After a rain. They click upon themselves  
As the breeze rises, and turn many-colored  
As the stir cracks and crazes their enamel.  
Soon the sun's warmth makes them shed crystal shells  
Shattering and avalanching on the snow-crust—    
Such heaps of broken glass to sweep away  
You'd think the inner dome of heaven had fallen.  
They are dragged to the withered bracken by the load,  
And they seem not to break; though once they are bowed  
So low for long, they never right themselves:  
You may see their trunks arching in the woods  
Years afterwards, trailing their leaves on the ground  
Like girls on hands and knees that throw their hair  
Before them over their heads to dry in the sun.  